config/routes.rb
EslJobs::Application.routes.draw do
  get 'account/index'

  resources :company_employees

  resources :experiences

  get "school_search_results/index"
  resources :employee_search_results
  resources :school_search_results
  resources :job_search_results
  resources :videos

  resources :pictures

  resources :role_types

  resources :educations

  resources :reviews
  
  

  default_url_options :host => "/"
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
end
  get "advertise/index"
  get "contact/index"
  get "about/index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "job_types/index"
  get "home/index"
  get "countries/index"
  get "job_posts/index", :path => "esl-jobs"
  resources :job_posts, :path => "esl-teaching-jobs"
  resources :countries, :path => "esl-jobs"
  resources :job_types
  resources :about
  resources :contact
  resources :advertise

   root 'job_posts#index'
  get '/users/:id', :to => 'users#show', :as => :user
  resources :users

  

  
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
    user ||= User.new
    can :manage, :all if user.role == "admin"
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/country.rb
class Country < ActiveRecord::Base
  extend FriendlyId
  friendly_id :countryname, use: :history
  def should_generate_new_friendly_id?
    new_record?
  end
  
  has_many :job_posts
   validates :countryname, presence: true,
                    length: { minimum: 3 }
  def display_name
    countryname
  end
  

end

app/models/education.rb
class Education < ActiveRecord::Base
    validates_presence_of :school, :degree, :date, :user_id
end

app/models/experience.rb
class Experience < ActiveRecord::Base
end

app/models/job_post.rb
class JobPost < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :history
  def should_generate_new_friendly_id?
    new_record?
  end
  
  def normalize_friendly_id(string)
  super[0..80]
  end

  belongs_to :country
  belongs_to :job_type
  belongs_to :user
  validates_uniqueness_of :title
  validates :title, :description, :country_id, presence: true
  validates_length_of :description, :minimum => 50                  

  def self.search(search, countrysearch = nil)
    
    @countryid = Country.find_by(:countryname => countrysearch ) 
    
    if @countryid.blank?
        where('(title LIKE? OR description LIKE?)', "%#{search}%","%#{search}%")
    else
      where('(title LIKE? OR description LIKE?) AND country_id=?', "%#{search}%","%#{search}%", "#{@countryid.id }")
    end
  end
  
  def self.advancesearch(keyword = nil, countrysearch = nil, datesearch= nil)
    @countryid = Country.find_by(:countryname => countrysearch )
    where('(title LIKE? OR description LIKE?)', "%#{keyword}%","%#{keyword}%") if keyword.blank? 
    keywordsql= '(title LIKE\'%'+keyword+'%\' OR description LIKE\'%'+keyword+'%\')' unless keyword.blank?
    
    unless keyword.blank? || @countryid.blank?
    addand = ' AND '
    end
    
    unless keyword.blank? && @countryid.blank?
      unless datesearch.blank?
        dateand = ' AND '
      end
    end
    
    countrysql = addand.to_s + 'country_id ='+@countryid.id.to_s unless @countryid.blank?
    datesearch = dateand.to_s + '`created_at` BETWEEN \'' + datesearch.to_i.days.ago.to_s + '\' AND \'' + 0.days.ago.to_s + '\'' unless datesearch.blank?
    where(keywordsql.to_s+countrysql.to_s + datesearch.to_s)

  end

end

app/models/job_posts.rb
class JobPosts < ActiveRecord::Base
end

app/models/job_type.rb
class JobType < ActiveRecord::Base
  has_many :job_posts
  def display_name
    type_title
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
     mount_uploader :pic_url, AvatarUploader
    belongs_to :user
    
    validate :avatar_size_validation
     private
  
  def avatar_size_validation
    errors[:pic_url] << "should be less than 1MB" if pic_url.size > 1.megabytes
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
    validates_presence_of :rating, :reviewpost
end

app/models/role_type.rb
class RoleType < ActiveRecord::Base
    has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :pictures
  belongs_to :role_type
  has_many :job_posts
  mount_uploader :avatar, AvatarUploader
  validates :username, format: { with: /\A[a-zA-Z0-9]+\Z/ }
  validates_uniqueness_of :username
  validates :first_name, :last_name, :country ,presence: true
  include Mailboxer::Models::Messageable
  validates_length_of :first_name, :last_name , :maximum => 30
  validates_length_of :businessname, :maximum => 100
  
  validates_uniqueness_of :username

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  ROLES = %w[business individual]
  
  extend FriendlyId
  friendly_id :username
  
  
  acts_as_messageable

  def mailboxer_name(object)
  
  end

  def mailboxer_email(object)
     
  end
  
  def self.teacher_search(keyword = nil, countrysearch = nil)

    if countrysearch.blank?
      where('(username LIKE? OR first_name LIKE?)', "%#{keyword}%","%#{keyword}%")
    else
      where('(username LIKE? OR first_name LIKE?) AND country=?', "%#{keyword}%","%#{keyword}%", "#{countrysearch }")
    end
  end
  
end

app/models/video.rb
class Video < ActiveRecord::Base
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
       @job_posts = JobPost.all
       @countries = Country.all
       @job_types= JobType.all
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mailbox_helper.rb
module MailboxHelper
  def unread_messages_count
    mailbox.inbox(:unread => true).count(:id, :distinct => true)
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/home/_container.html.erb
		<div class="main-area fix">
			<div class="container">
				<div class="row">
					<div class="col-md-10 col-sm-10 main-area-body fix">
						<div class="bannar fix">
							<img src="/assets/img/bannar.jpg" alt="" />
						</div>
						<section class="job_area fix">
							<h2><%= @container_title %> </h2>
							<div class="row">
								<div class="col-md-9 col-sm-9 all-job-area">
                   <% @job_posts.each do |job_post| %>
									<div class="col-md-4 col-sm-6 single_job_area">
                    <% if job_post.jobslink.blank? %>
                     <% @abc= job_post_path(job_post) %>
                    <% else %>
                    <% @abc= job_post.jobslink %>
                    <% end %>
                    
                    <%= link_to @abc , :target=> "_blank" do %>
										<div class="single_job fix">
											<div class="published_date fix">
												<p><%= job_post.created_at.strftime("%d %b. %Y") %></p>
											</div>
											<section class="job-descrip fix">
												<p><%= raw(strip_tags(job_post.title)[0,100]) %></p>
											</section>
											<div class="sallery fix">
												<p>$540 per month</p>
											</div>
											<div class="place_apply fix">
												<p class="place"><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span><%= job_post.country.countryname %></p>
												<p class="apply"><%=link_to "Read more", job_post %></p>
											</div>
										</div>
									</div>
                  <% end %>
                  <% end %>
									<div class="col-md-12 col-sm-12">
										<nav class="job-paginition">
											<ul class="pagination">
												<li>
	<%= will_paginate @job_posts,:inner_window => 2 %> 
												</li>
											</ul>
										</nav>
									</div>
								</div>

app/views/home/_featured_teacher.html.erb
	<!-- Featured Teachers Section -->
     <section class="ft-sec">
   	<div class="container">
    	<div class="row featured-teachers">  
                
                <div class="trt-cover">
                    <h1>Featured <span>Teachers</span></h1>
                    <div class="heading-border">
                    	<span class="line-border-left"></span>
                        <span class="left-circle"></span>
                        <span class="center-circle"></span>                        
                        <span class="left-circle"></span>
                        <span class="line-border-right"></span>
                    </div>
                </div>
                
                
            <% @individualusers.each do |indivuser| %>    
				<div class="col-md-3 ft-single-box">
                	<div class="teacher-img-cover">
                    	<img class="thumb-size" src="<%= indivuser.avatar.blank? ? asset_path('profile-placeholder.jpg') : indivuser.avatar.thumb.url %>" class="img-responsive">
                        <a href="<%= user_path(indivuser) %>"><span class="plus-icon">+</span></a>
                    </div>
                    <div class="clearfix"></div>
                    <div class="teacher-text">
                    	<h3><a href="<%= user_path(indivuser) %>"><%= indivuser.first_name %> <%= indivuser.last_name %></a></h3>
                        <p>Teacher</p>
                        <div class="location">
                            	<i class="fa  fa-map-marker"></i>
                                 <%= indivuser.country %>
                            </div>
                    </div>           
            </div>
            <% end %>
            <div class="clearfix"></div>
              <div class="view-all-teachers text-center">
                    <a href="<%= employee_search_results_path %>" class="viewallteachers-btn col-md-3">View All Teachers</a>
                </div>  
      
            
        </div>
    </div>
   </section>   

app/views/home/_footer.html.erb
        <!-- Footer -->
		<footer class="footer">
            <div class="footer-copyright">
           		 <div class="container">
                    <div class="row">
                    <div class="col-md-6 col-sm-12 col-xs-12 footer-links pull-right">
                            <ul>
                                <li><a href="/about">About Us</a></li>
                                <li><a href="/advertise">Advertise</a></li>
                                <li><a href="#">Terms</a></li>
                                <li><a href="#">Privacy Policy</a></li>
                                <li><a href="contact">Contact</a></li>                        
                            </ul>
                        </div>
                        <div class="col-md-6 col-sm-12 col-xs-12 pull-left">
                              <p> © ESL Jobs Lounge. All rights reserved. </p>
                        </div>
                        
                    </div>
           		 </div>        
            </div>
            <div class="footer-social-media">
            	<div class="container">
                	<div class="row">
                    <div class="col-md-12 socialMediaHeader">
                    <h4>Connect with us</h4>
                	<ul>
                    	<li><a href="https://www.facebook.com/pages/ESL-Jobs-Lounge/528664423908203"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="https://twitter.com/esljobslounge"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="https://plus.google.com/114631577984478173601/"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="#"><i class="fa fa-youtube"></i></a></li>                       
                    </ul>
                </div>
                    </div>
                </div>
            </div>
        </footer>

	
	<!-- Footer -->
	
	
    
    <!-- jQuery Resources-->
  <!--  <script src="/assets/js/jquery.js"></script> -->
    <!-- Bootstrap Core JavaScript -->
    <script src="<%= asset_path('js/bootstrap-editable.js') %>"></script>
   
    <script src="<%= asset_path('js/bootstrap.min.js') %>"></script>
    
    <!-- Custom Script -->
    <script src="<%= asset_path('js/custom-script.js') %>"></script>

app/views/home/_header.html.erb
<body id="page-top" data-target=".navbar-fixed-top" class="individualprofile-page">
    
    <!-- Header -->
    <header class="header">

	<div class="div-top-header">	
	
    <!--Branding and Main Navigation-->
<nav id="primaery-navbar" class="navbar navbar-default" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="container">
            <div class="col-md-3 col-sm-3 col-xs-12">          
			     <a class="navbar-brand" data-no-turbolink href="<%= root_path %>"><span>ESL</span> Jobs Lounge</a>
            </div>
            <div class="col-md-8 col-sm-8 col-xs-12 small-right pull-right">
                <% if user_signed_in? %>
                 <div class="col-md-4 col-xs-12 col-sm-3 pull-right login-signup-btn">
                    <a class="sign-in-login-btn green-btn dropdown-toggle camelcase"  data-toggle="dropdown" href="#">
                    <i class="fa fa-user"></i> 
                    <%= current_user.first_name %>
                    </a>
                      <ul class="dropdown-menu">
                        <li><a href="<%= user_path(current_user) %>">Profile</a></li>
                        <li><a href="<%= mailbox_inbox_path %>">Inbox</a></li>
                        <li><a href="<%= destroy_user_session_path %>">Sign out</a></li>
                      </ul>
                <% else %>
                <div class="col-md-2 col-xs-12 col-sm-3 pull-right login-signup-btn">
                <a class="sign-in-login-btn green-btn" href="<%= new_user_registration_path %>">
                    <i class="fa fa-user-plus"></i> 
                    Sign Up                                      
                    </a>
                <% end %>
        
                </div>
                <div class="col-md-2 col-xs-12 col-sm-3 pull-right login-signup-btn">
                     <% if user_signed_in? %>
                    <!--<a class="sign-in-login-btn" data-no-turbolink href="<%= user_path(current_user) %>">-->
                    <!--<i class="fa fa-user-plus"></i> -->
                    <!--Profile-->
                    <!--</a> -->
                    <% else %>
                    <a class="sign-in-login-btn" href="<%= new_user_session_path %>">
                    <i class="fa fa-sign-in"></i> 
                    Login
                    </a>
                    <% end %>

                </div> 
                
                <% if user_signed_in? %>
                   <div class="col-md-2 col-xs-12 col-sm-3 pull-right login-signup-btn">                 
                    <!--<a class="sign-in-login-btn" data-no-turbolink href="<%= mailbox_inbox_path %>">-->
                    <!--<i class="fa fa-user-plus"></i> -->
                    <!--Inbox-->
                    <!--</a> -->
                    </div>
                    <div class="col-md-7 col-xs-12 col-sm-6 pull-right login-signup-btn">
                <% else %>
                <div class="col-md-8 col-xs-12 col-sm-6 pull-right login-signup-btn">
                <% end %>

               <div class="col-md-12 nopadding">
               <!-- <div class="category-field">
                 <select name="" id="input" class="form-control" required="required">                         
                          <option value=""><i class="fa fa-search"></i> <span class="hide-text">Jobs</span></option>
                          <option value="">Teachers</option>
                          <option value="">Employers</option>
                          <option value="">Forum</option>
                        </select>
                        <i class="fa fa-angle-down"></i>                        
               </div> -->
                <form class="navbar-form pull-right" role="search" method="get" id="searchform" action="job_search_result">
                <div class="input-group cutsominput-group">
                    <div class="input-group-btn">
                        <button type="button" id="searchcategory" value="Jobs" class="btn btn-cat" data-toggle="dropdown" aria-expanded="false">Jobs <span class="caret"></span></button>
        
                        <ul id="searchdropdown" class="dropdown-menu" role="menu">
                            <li><a href="javascript:void(0)">Jobs</a></li>
                            <li><a href="javascript:void(0)">Teachers</a></li>
                            <li><a href="javascript:void(0)">Employers</a></li>
                        </ul>
                    </div>
                    <input type="text" class="form-control search-field" value="" placeholder="Search..." name="keyword" id="search_field">
                    <div class="input-group-btn">
                        <button type="submit" id="searchsubmit" value="Search" class="btn btn-cat btn-green"><span class="glyphicon glyphicon-search"></span></button>
                    </div>
                </div>
            </form> 
               </div>
               <!-- <div class="col-md-8 nopl">
                    <div class="search-filed">
                    <form>
                        
                        <input type="text" name="" id="" placeholder="Search your keyword..">
                        <button type="submit"><i class="fa fa-search"></i></button>
                    </form>
                    </div>
                    </div> -->
               </div>   
            </div>
    </nav>
    
   </div>

app/views/home/_how_works.html.erb
	<!-- How it works Section -->
        <section class="how-it-works-sec">
            <div class="container">
                <div class="row how-itworks">       	
                	
                <div class="trt-cover">
                    <h1>How it <span>Works?</span></h1>
                    <div class="heading-border">
                    	<span class="line-border-left"></span>
                        <span class="left-circle"></span>
                        <span class="center-circle"></span>                        
                        <span class="left-circle"></span>
                        <span class="line-border-right"></span>
                    </div>
                </div>
                
                
                    <div class="col-md-4 how-it-works-box">
                    	<div class="icon-cover">
                        	<i class="fa fa-briefcase"></i>
                        </div>
                        <h2>Create a Profile</h2>
                        <p>Start by creating a profile on our website. Teachers can create an individual profile and apply to jobs. Schools or businesses can create a business profile and post jobs.
 </p>
                    </div>
                    
                    <div class="col-md-4 how-it-works-box">
                    	<div class="icon-cover">
                        	<i class="fa fa-user"></i>
                        </div>
                        <h2>Post a Job </h2>
                        <p>Post jobs and attract teachers from around the world.</p>
                    </div>
                    
                    <div class="col-md-4 how-it-works-box">
                    	<div class="icon-cover">
                        	<i class="fa fa-money"></i>
                        </div>
                        <h2>Hire the Perfect Teacher</h2>
                        <p>Review applicants and hire the right teacher to join your organization!</p>
                    </div>
                </div>
                
               
            </div>
        </section>
        

app/views/home/_index.html.erb
<%= render 'header'%>	

<%= render 'subheader'%>

<%= render 'container'%>
	
<%= render 'leftsidebar'%>

<%= render 'footer'%>

app/views/home/_latest_job.html.erb
    <!-- Latest Jobs section -->
   <section class="latest-jobs-sec">
   	<div class="container">
    	<div class="row latest-job">        	
            <div class="col-md-10 latest-job-left-col">
            	
            	<div class="trt-cover">
                    <h1>Latest <span>Jobs</span></h1>
                    <div class="heading-border">
                    	<span class="line-border-left"></span>
                        <span class="left-circle"></span>
                        <span class="center-circle"></span>                        
                        <span class="left-circle"></span>
                        <span class="line-border-right"></span>
                    </div>
                </div>
            	
   <% @job_posts.each do |job_post| %>
                <div class="col-md-4 lates-jobs-single-box">
                    <a <%= job_post.jobslink.blank? ? '' : 'target="_blank"' %> href="<%=job_post_path(job_post) %>">
                    <div class="panel panel-default">
                        <div class="panel-body">
                        	<h3 class="job-title"><%= raw(strip_tags(job_post.title).split[0..5].join(" ")) %></h3>
                            <p class="job-description"><%= raw(strip_tags(job_post.description).split[0..28].join(" ")) %></p>
                            <div class="location">
                            	<i class="fa  fa-map-marker"></i>
                                <%= job_post.country.countryname %>
                            </div>
                            <div class="job-price">
                            	<%= job_post.created_at.strftime("%d %b, %Y") %>
                            </div>
                            <div class="job-apply">
                            	Apply
                            </div>
                            <div class="clearfix"></div>
                        </div>                        
                    </div>
                    </a>
                </div>
                       <% end %>  
 
                <div class="clearfix"></div>
                
      			<div class="view-all-jobs text-center">
                	<a href="<%= job_search_results_path %>" class="viewalljobs-btn col-md-3">View All Jobs</a>
                </div>
   
                
            </div>
            <div class="col-md-2 latest-job-right-col text-center">
            	<img src="<%= asset_path('googl-ad.jpg') %>" class="img-responsive">            
            </div>
            
        </div>
    </div>
   </section>

app/views/home/_subheader.html.erb
    <script src="<%= asset_path('js/jquery.select-to-autocomplete.js') %>"></script>   
	<script>
	  (function($){
	    $(function(){
	      $('select').selectToAutocomplete();
	    });
	  })(jQuery);
	</script>
   <div class="header-cover">
		<div class="container">
			<div class="row">
				
				<div class="search-form-header">
                <div class="col-md-12">
                    <%= form_tag job_search_results_path, :method => 'get' do %>
                        <div class="col-md-5 col-sm-6 col-xs-12 text-field-cover">
    					   <input type="text" name="keyword" placeholder="Job title keyword">
                        </div>
                        <div class="col-md-5 col-sm-6 col-xs-12 text-field-cover">
                       <select name="countrysearch" id="country-selector" autofocus="autofocus" autocorrect="off" placeholder="Country" autocomplete="off">
                          <option value="" selected="selected">Select Country</option>
       						 <% @countries.each do |country| %>
    						     <option value="<%= country.countryname %>"><%= country.countryname %> </option>
    						 <%end%>
                        </select>
    					 <!--   <div class="select-country">
                            <select>
                                <option value="volvo">Select country</option>
                                <option value="saab">United Kingdom</option>
                                <option value="mercedes">United State</option>
                                <option value="audi">Pakistan</option>
                            </select> 
                            <span class="down-arrow">
                                <i class="fa fa-caret-down"></i>
                            </span>
                        </div> -->
                        </div>
                    
                        <div id="buttons" class="col-md-2 search-job-btn">
                        <button type="submit" class="btn green">Search</button>
                        <a href="<%= job_search_results_path %>">Advanced Search</a>                                                 
                        </div>
                    
                    </div>
                    <div class="clearfix"></div>
				</div>
				
			<% end %>
			</div>
		</div>
	</div>
   </div>
       
    </header>

app/views/home/_top_rated_school.html.erb
	<!-- Our top rated teachers section -->
	<section class="trt-sec">
    	<div class="container">
        	<div class="row">
            	<div class="trt-cover">
                	<h1>Featured <span>Employers</span></h1>
                    <div class="heading-border">
                    	<span class="line-border-left"></span>
                        <span class="left-circle"></span>
                        <span class="center-circle"></span>                        
                        <span class="left-circle"></span>
                        <span class="line-border-right"></span>
                    </div>
                    
                    <div class="trt-carsouel-slider-cover"> 
                <div class="carousel slide" data-ride="carousel" data-type="multi" data-interval="3000" id="myCarousel">
                <div class="carsouel-cover">
                <div class="carousel-inner">
                <div class="item active">
                    <% @businessusers.each do |busiuser| %>
                    <div class="col-md-4 col-sm-6 col-xs-12">
                        <div class="top-rated-single-employe">
                                                <h2><a href="<%= user_path(busiuser) %>"><%= busiuser.businessname %></a></h2>                      
                                                <div class="location">
                                                    <i class="fa  fa-map-marker"></i>
                                                      <%= busiuser.country %>
                                                </div>  
                                                <div class="start-rating-cover">
         <% @reviewstop = Review.where(:review_to => busiuser.id) %>                            
          <% totalrating = 0 %>
           <% unless @reviewstop.blank? %>      
           <% @reviewstop.each do |reviewrate| %>
           <% totalrating = totalrating + reviewrate.rating %>
            <% end %>

            <% mainrate = totalrating / @reviewstop.count %>
          <% else %>
          <% mainrate = 0 %>
          <% end %>                                                
        <fieldset class="rating">
        <% 5.downto(1) do |i| %>    
        <input type="radio" id="star<%= i %>" disabled='disabled' <%= "checked" if i == mainrate %> value="<%= i %>"  name="rating" value="<%= i %>" /><label class = "full" for="star<%= i %>" title="Awesome - <%= i %> stars"></label>
        <% end %>
        </fieldset>
        <div class="clearfix"></div>
                                                </div>  
                                                <div class="job-label">Latest Job:</div>
                                               <h4 class="slide-latest-job">
                                                    <% @jobpostbyschools = JobPost.where(:user_id => busiuser.id).limit(1) %>
                                                
                                                <% if @jobpostbyschools.blank? %>   
                                                    <a href="#"><i class="fa fa-briefcase"></i>No Job posted by this user</a>
                                                <% end %>
                                                <% @jobpostbyschools.each do |schoollatestjob| %>
                                                    <a href="<%= job_post_path(schoollatestjob) %>"><i class="fa fa-briefcase"></i>
                                                 <%= schoollatestjob.title %>
                                                    </a>
                                                <% end %>    
                                                    </h4>                                         
                                            </div>
                                            <div class="employe-pic">
                                                    <img class="thumb-size" src="<%= busiuser.avatar.blank? ? asset_path('profile-placeholder.jpg') : busiuser.avatar.thumb.url %>" class="img-responsive">
                                            </div>    
                    </div>
                    <% end %>
                </div>
                
                </div>
                </div>
                <!--<a class="left carousel-control" href="#myCarousel" data-slide="prev"><i class="fa fa-angle-left"></i></a>-->
                <!--<a class="right carousel-control" href="#myCarousel" data-slide="next"><i class="fa fa-angle-right"></i></a>-->
                </div>

                    </div>
                </div>
                <div class="view-all-employers text-center">
                    <a href="<%= school_search_results_path %>" class="viewallemployers-btn col-md-3">View All Employers</a>
                </div>
            </div>
        </div>
    </section>