config/routes.rb
EslJobs::Application.routes.draw do
  get 'account/index'

  resources :company_employees

  resources :experiences

  get "school_search_results/index"
  resources :employee_search_results
  resources :school_search_results
  resources :job_search_results
  resources :videos

  resources :pictures

  resources :role_types

  resources :educations

  resources :reviews
  
  

  default_url_options :host => "/"
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
end
  get "advertise/index"
  get "contact/index"
  get "about/index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "job_types/index"
  get "home/index"
  get "countries/index"
  get "job_posts/index", :path => "esl-jobs"
  resources :job_posts, :path => "esl-teaching-jobs"
  resources :countries, :path => "esl-jobs"
  resources :job_types
  resources :about
  resources :contact
  resources :advertise

   root 'job_posts#index'
  get '/users/:id', :to => 'users#show', :as => :user
  resources :users

  

  
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end  
end

app/models/job_post.rb
class JobPost < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :history
  def should_generate_new_friendly_id?
    new_record?
  end
  
  def normalize_friendly_id(string)
  super[0..80]
  end

  belongs_to :country
  belongs_to :job_type
  belongs_to :user
  validates_uniqueness_of :title
  validates :title, :description, :country_id, presence: true
  validates_length_of :description, :minimum => 50                  

  def self.search(search, countrysearch = nil)
    
    @countryid = Country.find_by(:countryname => countrysearch ) 
    
    if @countryid.blank?
        where('(title LIKE? OR description LIKE?)', "%#{search}%","%#{search}%")
    else
      where('(title LIKE? OR description LIKE?) AND country_id=?', "%#{search}%","%#{search}%", "#{@countryid.id }")
    end
  end
  
  def self.advancesearch(keyword = nil, countrysearch = nil, datesearch= nil)
    @countryid = Country.find_by(:countryname => countrysearch )
    where('(title LIKE? OR description LIKE?)', "%#{keyword}%","%#{keyword}%") if keyword.blank? 
    keywordsql= '(title LIKE\'%'+keyword+'%\' OR description LIKE\'%'+keyword+'%\')' unless keyword.blank?
    
    unless keyword.blank? || @countryid.blank?
    addand = ' AND '
    end
    
    unless keyword.blank? && @countryid.blank?
      unless datesearch.blank?
        dateand = ' AND '
      end
    end
    
    countrysql = addand.to_s + 'country_id ='+@countryid.id.to_s unless @countryid.blank?
    datesearch = dateand.to_s + '`created_at` BETWEEN \'' + datesearch.to_i.days.ago.to_s + '\' AND \'' + 0.days.ago.to_s + '\'' unless datesearch.blank?
    where(keywordsql.to_s+countrysql.to_s + datesearch.to_s)

  end

end

app/models/job_posts.rb
class JobPosts < ActiveRecord::Base
end

app/controllers/job_posts_controller.rb
class JobPostsController < ApplicationController
  def index
    @job_posts = JobPost.paginate(:page => params[:page], :per_page => 39, total_entries: 100).order("updated_at DESC").limit(9)

    @countries = Country.all
    @user = User.all
    @individualusers = User.where( :role_type_id => 1).order("rand()").limit(4)
    @businessusers = User.where( :role_type_id => 2).order("rand()").limit(3)
  end

  def new
   @countries = Country.all
   @title="Add Jobs"
   @job_post = JobPost.new
  end

  def create
  @job_post = JobPost.new(job_post_params)
 
  if @job_post.save
  redirect_to @job_post
    else
      render 'new'
    end
  end
  
  def edit
  @job_post = JobPost.friendly.find(params[:id])
  end
  
  def show
  @user = User.all
  @countries = Country.all
  @job_types = JobType.all
  @job_post = JobPost.friendly.find(params[:id])
  unless @job_post.jobslink.blank?
    redirect_to @job_post.jobslink
  end
  @userjobpost = JobPost.where(:user_id => @job_post.user_id)
  end

  def update
  @job_post = JobPost.friendly.find(params[:id])
  if @job_post.update(job_post_params)
    redirect_to @job_post
  else
    render 'edit'
  end
  end

  def destroy
  @job_post = JobPost.friendly.find(params[:id])
  @job_post.destroy
  redirect_to user_path(current_user) + '?back_to=jobs'
  end

  private
  def job_post_params
  params.require(:job_post).permit(:title, :description, :city  , :jobslink, :salary, :company, :country_id , :job_type_id, :user_id, :required_skills).merge(:user_id => current_user.id)
  end
  
end

app/helpers/job_posts_helper.rb
module JobPostsHelper
end

app/views/job_posts/_edit.html.erb
<p>Edit Posts</p>
<%= render 'job_posts/formEdit'%>

app/views/job_posts/_formEdit.html.erb
<%= form_for :job_post, url: job_post_path(@job_post), method: :patch do |f| %>
  <% if @job_post.errors.any? %>
  <div id="error_explanation">
    <p><%= pluralize(@job_post.errors.count, "error") %> prohibited
      this post from being saved:</p>
    <ul>
    <% @job_post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
<p>
	<%=f.label :title%> <br />
	<%=f.text_field :title%>
</p>
<p>
	<%=f.label :description%> <br />
	<%=f.text_area :description%>
</p>

<p>
	<%=f.label :jobslink%> <br />
	<%=f.text_field :jobslink%>
</p>
<p>
	<%=f.label :salary%> <br />
	<%=f.text_field :salary%>
</p>
 <div class="field">
    <%= f.label :CountryName %><br />
<%= f.collection_select(:country_id, Country.all, :id, :countryname, include_blank: false) %>

<p>
	<%=f.label :company%> <br />
	<%=f.text_field :company%>
<p>

<p><%= f.submit %></p>
<% end %>

app/views/job_posts/_formNew.html.erb
<%= form_for :job_post, url: job_posts_path do |f| %>
  <% if @job_post.errors.any? %>
  <div id="error_explanation">
    <p><%= pluralize(@job_post.errors.count, "error") %> prohibited
      this post from being saved:</p>
    <ul>
    <% @job_post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
<p>
	<%=f.label :title%> 
	<%=f.text_field :title%>
</p>
<p>
	<%=f.label :description%> 
	<%=f.text_area :description%>
</p>

<p>
	<%=f.label :jobslink%> 
	<%=f.text_field :jobslink%>
</p>
<p>
	<%=f.label :salary%>
	<%=f.text_field :salary%>
</p>
<p>
    <%= f.label :CountryName %>
<%= f.collection_select(:country_id, Country.all, :id, :countryname, include_blank: false) %>
</p>
<p>
    <%= f.label :JobType %>
<%= f.collection_select(:job_type_id, JobType.all, :id, :type_title, include_blank: false) %>
</p>

<p>
	<%=f.label :company%> 
	<%=f.text_field :company%>
<p>

<p><%= f.submit %></p>
<% end %>

app/views/job_posts/edit.html.erb
<p>Edit Posts</p>
<%= render 'job_posts/formEdit'%>

app/views/job_posts/index.html.erb
<%   
 @page_title= "ESL Jobs Lounge | Teach English Jobs Abroad | ESL Teaching JOBS"
 @page_keywords="esl jobs, esl teaching jobs, esl jobs lounge,teach english"
 @page_description="ESL Jobs | Your one stop to find your next ESL Teaching Job"
 @page_author="ESL Teaching JOBS Lounge"
 @container_title= "Latest ESL Teaching Jobs"
%>
<%= render 'home/header'%>	
<% flash.each do |name, msg| %>
  <div class="alert alert-info text-center"> 
  <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>
<%= render 'home/subheader'%>
<%= render 'home/latest_job'%>
<%= render 'home/top_rated_school'%>
<%= render 'home/featured_teacher'%>
<%= render 'home/how_works'%>
<%= render 'home/footer'%>

app/views/job_posts/new.html.erb
<%= render 'home/header'%>
</header>
   <section class="page-heading-sec">    
        <div class="container">
            <div class="row">
            <div class="page-heading">
                 <h1>Post a New Job</h1>            
            </div>       
        </div>
    </div>

    </section>
 

  <% if current_user.role_type.name == "business" %>
    <!-- Login form section -->
    <section class="post-a-job-sec">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-sm-12 col-xs-12 col-md-offset-2">
				   <%= form_for :job_post, url: job_posts_path do |f| %>
				  <% if @job_post.errors.any? %>
				  <div id="error_explanation">
				    <p><%= pluralize(@job_post.errors.count, "error") %> prohibited
				      this post from being saved:</p>
				    <ul>
				    <% @job_post.errors.full_messages.each do |msg| %>
				      <li><%= msg %></li>
				    <% end %>
				    </ul>
				  </div>
				  <% end %> 
  
                <div class="post-job-form">
                	<div class="single-field">
	                	<div class="col-md-4"><label>Job Title <span class="required-field">*</span></label></div>
	                	<div class="col-md-8"><%=f.text_field :title , :required => true %></div>
                	</div>
                	<div class="single-field">
	                	<div class="col-md-4"><label>City <span class="required-field">*</span></label></div>
	                	<div class="col-md-8"><%=f.text_field :city, :required => true%></div>
                	</div>

                	<div class="single-field">
	                	<div class="col-md-4"><label>Country <span class="required-field">*</span></label></div>
	                	<div class="col-md-8"><%= f.collection_select(:country_id, Country.all, :id, :countryname, include_blank: false) %></div>
                	</div>
					<div class="clearfix"></div>
                	<div class="single-field">
	                	<div class="col-md-4"><label>Salary <span class="required-field">*</span></label></div>
	                	<div class="col-md-8"><%=f.text_field :salary, :required => true%></div>
                	</div>

                	<div class="single-field">
	                	<div class="col-md-4"><label>Job Description <span class="required-field">*</span></label></div>
	                	<div class="col-md-8"><%=f.text_area :description, :required => true%></div>
                	</div>
                	
                	<div class="single-field">
	                	<div class="col-md-4"><label>Required Skills </label></div>
	                	<div class="col-md-8"><textarea  id="" name="required_skills"></textarea></div>
                	</div>

					
					<div class="single-field col-md-4 pull-right full-btn">
						<button type="submit" class="post-job-btn">Submit</button>
					</div>

                <div class="clearfix"></div>
                </div>
                
            </div> 
              
        </div>
    </section>
<% end %>
<% else %>
<div class="col-md-offset-3 top-buffer-3 bottom-buffer-3">You are not authorized person to post a job. You must sign up as business account to post a job.</div>
<div class="clearfix"></div>
<% end %>
<%= render 'home/footer'%>

app/views/job_posts/show.html.erb
 <%   
 @page_title= @job_post.title+ " | Esl Teaching Jobs Lounge"
 @page_keywords="esl jobs, esl teaching jobs, esl jobs in "+ @job_post.country.countryname + ", esl jobs lounge,teach english"
 @page_description="ESL JOBS in "+ @job_post.country.countryname+" : " + raw(strip_tags(@job_post.description)[0,256])
 @page_author="ESL Teaching JOBS Lounge"
 @container_title= ""
%>
 
<%= render 'home/header'%>	
</header>
    <section class="page-heading-sec job-desc-sec">    
        <div class="container">
            <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12 col-lg-12">     
            </div>  
        </div>
    </div>

    </section>
    
    <!-- Login form section -->
    <section class="job-description-sec">
        <div class="container">
            <div class="row">
            <div class="col-md-12">
            <h1 class="m-t-0"><%= @job_post.title %></h1>
            </div>
            <div class="col-md-9 col-sm-9 col-xs-12 col-lg-9">
               <div class="job-content">
               <div class="sidebar-job-des">
               <div class="row">
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div class="single-field-desc">
                        <div class="single-box-header">
                            <i class="fa fa-calendar"></i>
                            <span class="single-label">Date Posted</span>
                            <div class="clearfix"></div>
                        </div>
                        <p><%= @job_post.created_at.strftime("%d %b. %Y") %></p>
                    </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div class="single-field-desc">
                        <div class="single-box-header">
                            <i class="fa fa-map-marker"></i>
                            <span class="single-label">Location</span>
                            <div class="clearfix"></div>
                        </div>
                        <p><%= @job_post.country.countryname  %></p>
                    </div> 
                    </div> 

                   <!--  <div class="col-md-4">
                    <div class="single-field-desc">
                        <div class="single-box-header">
                            <i class="fa fa-user"></i>
                            <span class="single-label">Position</span>
                            <div class="clearfix"></div>
                        </div>                
                        <p>Tutoring Jobs</p>
                    </div> 
                    </div> --> 
                   <!--  <div class="col-md-4">
                    <div class="single-field-desc">
                         <div class="single-box-header">
                            <i class="fa fa-clock-o"></i>
                            <span class="single-label">Job Status</span>
                            <div class="clearfix"></div>
                        </div>
                        <p>Part-time</p>
                    </div> 
                    </div> -->
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div class="single-field-desc">
                        <div class="single-box-header">
                            <i class="fa fa-money"></i>
                            <span class="single-label">Salary</span>
                        <div class="clearfix"></div>
                        </div>                   
                        <p><%= @job_post.salary.blank? ? 'Negotiable' : @job_post.salary  %></p>
                    </div> 
                    </div>
                   <!--  <div class="col-md-4">
                    <div class="single-field-desc">
                        <div class="single-box-header">
                            <i class="fa fa-money"></i>
                            <span class="single-label">Expertise</span>
                        <div class="clearfix"></div>
                        </div>                   
                        <p>Hourly Rate</p>
                    </div> 
                    </div> -->
                </div>
                </div> 
                <div class="clearfix"></div>
                <div class="job-description-box">
                   <h3>Description</h3>
                <p><%= raw(@job_post.description) %>
</p>
 
<% if current_user.id != @job_post.user_id %>
<div class="col-md-4 col-md-offset-4">
<a href="<%=@job_post.jobslink.blank? ? new_conversation_path(:user => @job_post.user.id) : @job_post.jobslink  %>" class="green-button-common"><%= @job_post.jobslink.blank? ? 'Apply Job' : 'External Link'  %></a>
</div>
<% end %>
                <div class="clearfix"></div>
               </div>
               <% unless @job_post.user.blank? %>
               <div class="job-des-profile">
                    <div class="col-lg-2 col-md-3 col-sm-4 col-xs-12 nopadding">
                        <div class="job-profile-img">
                            <img class="thumb-size" src="<%= @job_post.user.avatar.blank? ? asset_path('profile-placeholder.jpg') : @job_post.user.avatar.thumb.url  %>">
                        </div>                        
                    </div>
                    <div class="col-lg-10 col-md-9 col-sm-8 col-xs-12">
                        <div class="job-profile-des">
                            <h3><a href="<%= user_path(@job_post.user) %>"><%= @job_post.user.first_name unless @job_post.user.first_name.blank? %> <%= @job_post.user.last_name unless @job_post.user.last_name.blank? %> (<%= @job_post.user.username unless @job_post.user.username.blank? %>)</a></h3>
                            <span class="designation"> <%= @job_post.user.businessname + " | " unless @job_post.user.businessname.blank?  %> <b></b> <%= @job_post.user.country + "Location: | " unless @job_post.user.country.blank?  %>  <b>Since:</b> <%= @job_post.created_at.strftime("%d %b. %Y") %> </span>
                            <p><%= raw(strip_tags(@job_post.user.about)[0,100]) unless @job_post.user.about.blank? %> </p> 
                            <div class="start-rating-cover">
        <fieldset class="rating pull-left">
        <input type="radio" id="star5" name="rating" value="5" /><label class = "full" for="star5" title="Awesome - 5 stars"></label>
        <input type="radio" id="star4half" name="rating" value="4 and a half" /><label class="half" for="star4half" title="Pretty good - 4.5 stars"></label>
        <input type="radio" id="star4" name="rating" value="4" /><label class = "full" for="star4" title="Pretty good - 4 stars"></label>
        <input type="radio" id="star3half" name="rating" value="3 and a half" /><label class="half" for="star3half" title="Meh - 3.5 stars"></label>
        <input type="radio" id="star3" name="rating" value="3" /><label class = "full" for="star3" title="Meh - 3 stars"></label>
        <input type="radio" id="star2half" name="rating" value="2 and a half" /><label class="half" for="star2half" title="Kinda bad - 2.5 stars"></label>
        <input type="radio" id="star2" name="rating" value="2" /><label class = "full" for="star2" title="Kinda bad - 2 stars"></label>
        <input type="radio" id="star1half" name="rating" value="1 and a half" /><label class="half" for="star1half" title="Meh - 1.5 stars"></label>
        <input type="radio" id="star1" name="rating" value="1" /><label class = "full" for="star1" title="Sucks big time - 1 star"></label>
        <input type="radio" id="starhalf" name="rating" value="half" /><label class="half" for="starhalf" title="Sucks big time - 0.5 stars"></label>
        </fieldset>
        <div class="clearfix"></div>
                                                </div>  
                        </div>
                    </div>
                  <div class="clearfix"></div>      
               </div>

               <div class="employer-similar-jobs">
                   <h2>Other job posted by <%= @job_post.user.username %></h2>
                   <div class="clearfix"></div>
                   <% @userjobpost.each do |userjobpost| %>
                   <div class="list-job-box">
                       <h5><a href="#"><%= userjobpost.title %> </a></h5>
                       <p> <%= raw(strip_tags(userjobpost.description)[0,300]) %></p>
                       <h6>Posted <%= userjobpost.created_at.strftime("%d %b. %Y") %></h6>
                       <div class="clearfix"></div>
                   </div>
                   <% end %>
               </div>
               <% end %>

               </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 img-add">
                <img src="<%= asset_path("google-ad-160.jpg") %>">          
            </div>
                
            </div> 
              
        </div>
    </section>
<%= render 'home/footer'%>

app/views/job_posts/show_previous.html.erb
 <%   
 @page_title= @job_post.title+ " | Esl Teaching Jobs Lounge"
 @page_keywords="esl jobs, esl teaching jobs, esl jobs in "+ @job_post.country.countryname + ", esl jobs lounge,teach english"
 @page_description="ESL JOBS in "+ @job_post.country.countryname+" : " + raw(strip_tags(@job_post.description)[0,256])
 @page_author="ESL Teaching JOBS Lounge"
 @container_title= ""
%>
 
<%= render 'home/header'%>	
	<div class="home_wrapper">

	<div class="container-fluid home_main_content">
	<div class="row-fluid">
		
		
	<div class="span9">
		
		<div class="row-fluid">
			
			<div class="span12">
				<table class="table table-striped">
					<tbody>
<br>
<div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- header ad -->
<ins class="adsbygoogle"
     style="display:inline-block;width:710px;height:90px"
     data-ad-client="ca-pub-3947968133656454"
     data-ad-slot="9732614529"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>
<h1>
  <%= @job_post.title %>
</h1>
 <td>
<p>
  <strong>Job Details:</strong><br/>
  <%= raw(@job_post.description) %>
</p>
<p>

<% if @job_post.salary.blank? %>
<% else %>
     <strong>Salary: </strong>
  <%= @job_post.salary %>
</p>
<% end %>

<% if @job_post.company.blank? %>
<% else %>
<p>
  <strong>Company:</strong>
  <%= @job_post.company %>
</p>
<% end %>

<% if @job_post.country.countryname.blank? %>
<% else %>
<p>
  <strong>Country: </strong>
  <%= @job_post.country.countryname %>
</p>
<% end %>
 
<p>
  <strong>Original Job Link: </strong>
  <%= link_to "Click here", @job_post.jobslink, :target => '_blank' %>
</p>
<!-- 
<p>
  <strong>salary:</strong>
  <%= @job_post.salary %>
</p>
<p>
  <strong>Job Types</strong>
  <%= @job_post.job_type.type_title %>
</p>
<p>
  <strong>Country id</strong>
  <%= @job_post.country.countryname %>
</p>
 
<p>
  <strong>company:</strong>
  <%= @job_post.company %>
</p>
-->
<br>
 <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- text ad -->
<ins class="adsbygoogle"
     style="display:inline-block;width:700px;height:90px"
     data-ad-client="ca-pub-3947968133656454"
     data-ad-slot="6328809722"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
<br>
<br/>

<h2>
  <strong><a style="float:left" href="/esl-jobs/<%= @job_post.country.countryname %>">Back to ESL JOBS in <%= @job_post.country.countryname %></a></strong>
</h2>

<h2>
  <strong><a style="float:right" href="/">Back to homepage</a></strong>
</h2>
</td>
					</tbody>
				</table>
			</div>
			
		</div>
	</div>

<%= render 'home/leftsidebar'%>
	</div>
	</div>
	</div> <!-- /container -->
<%= render 'home/footer'%>