config/routes.rb
EslJobs::Application.routes.draw do
  get 'account/index'

  resources :company_employees

  resources :experiences

  get "school_search_results/index"
  resources :employee_search_results
  resources :school_search_results
  resources :job_search_results
  resources :videos

  resources :pictures

  resources :role_types

  resources :educations

  resources :reviews
  
  

  default_url_options :host => "/"
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
end
  get "advertise/index"
  get "contact/index"
  get "about/index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "job_types/index"
  get "home/index"
  get "countries/index"
  get "job_posts/index", :path => "esl-jobs"
  resources :job_posts, :path => "esl-teaching-jobs"
  resources :countries, :path => "esl-jobs"
  resources :job_types
  resources :about
  resources :contact
  resources :advertise

   root 'job_posts#index'
  get '/users/:id', :to => 'users#show', :as => :user
  resources :users

  

  
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end  
end

app/models/picture.rb
class Picture < ActiveRecord::Base
     mount_uploader :pic_url, AvatarUploader
    belongs_to :user
    
    validate :avatar_size_validation
     private
  
  def avatar_size_validation
    errors[:pic_url] << "should be less than 1MB" if pic_url.size > 1.megabytes
  end
end

app/controllers/pictures_controller.rb
class PicturesController < InheritedResources::Base
   def index
    @pictures = Picture.where(:user_id => @user.id)
   end
  
   def new
     @picture = Picture.new
   end
   
     def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
         params[:picture].each {|param|
          @pictures = Picture.where(:user_id => current_user.id)
    }
         
        format.html { redirect_to user_path(current_user) + '?back_to=pictures', notice: 'Picture was successfully created.' }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
    end

  def destroy
  @picture = Picture.find(params[:id])
  @picture.destroy
  redirect_to user_path(current_user) + '?back_to=pictures', notice: 'Picture was successfully deleted.'
  @pictures = Picture.where(:user_id => current_user.id)
  end

  private

    def picture_params
      params.require(:picture).permit(:pic_url, :description, :users_id, :pic_url, :pic_url_cache).merge(:user_id => current_user.id)
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<div id="new_picture">
<div id="addpic" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Add Content</h4>
      </div>
      <div class="modal-body">
          <%= form_for @picture, remote: true, authenticity_token: true do |f| %>
  <div class="form-group">
    <label for="email">Upload file (.jpg, .png etc)</label>
    <%= f.file_field :pic_url,:onchange =>"validateFiles(this);", :class=>"form-control",
        :data => {:max_file_size => 1.megabytes}%>

    <%= f.hidden_field :pic_url_cache %>
  </div>
  <div class="form-group">
    <label for="pwd">Picture Detail</label>
    <%= f.text_area :description, :class=>"modal-textarea" %>
  </div>  

      </div>
      <div class="modal-footer">
        <%= f.submit 'Create', :class=>"send-msg" %>
      </div>
      <% end %>
    </div>

  </div>
</div>
</div>
<script>
  function validateFiles(inputFile) {
  var maxExceededMessage = "This file exceeds the maximum allowed file size (1 MB)";
  var extErrorMessage = "Only image file with extension: .jpg, .jpeg, .gif or .png is allowed";
  var allowedExtension = ["jpg", "jpeg", "gif", "png"];
  
  var extName;
  var maxFileSize = $(inputFile).data('max-file-size');
  var sizeExceeded = false;
  var extError = false;
  
  $.each(inputFile.files, function() {
    if (this.size && maxFileSize && this.size > parseInt(maxFileSize)) {sizeExceeded=true;};
    extName = this.name.split('.').pop();
    if ($.inArray(extName, allowedExtension) == -1) {extError=true;};
  });
  if (sizeExceeded) {
    window.alert(maxExceededMessage);
    $(inputFile).val('');
  };
  
  if (extError) {
    window.alert(extErrorMessage);
    $(inputFile).val('');
  };
}
</script>

app/views/pictures/_index.html.erb
    <div class="picture_list">
    <% @pictures.each do |picture| %>

                             <div class="col-md-3 text-center">                        
                          <div class="portfolio-box">    
                          <% if picture.pic_url.blank?
                          @picurl =  asset_path('no-image.jpg')
                           else
                          @picurl = picture.pic_url
                          end %>
                          
                              <img src="<%= @picurl %>">
                              <div class="clerarfix"></div>                            
                            <p><%= picture.description %></p>
                            <% if @right_user %>
                            <a href="/pictures/<%= picture.id %>" data-method="delete" data-confirm="Are you sure?" class="close-button-x"><span>X</span></a>
                            <% end %>
                          </div>
                        </div>
    <% end %>

      </div>
<div id="incomplete_pictures"></div>

app/views/pictures/create.js.erb
$('.picture_list').hide();
$('#incomplete_pictures').empty();
$('#incomplete_pictures').append('<%= j render("index") %>');
$('#new_link_picture').show();
$('#addpic').modal('hide');

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<h1>Listing pictures</h1>

<table>
  <thead>
    <tr>
      <th>Pic url</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.pic_url %></td>
        <td><%= picture.description %></td>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New picture</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/new.js.erb
$('#new_link_picture').hide().after('<%= j render("form") %>');

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pic url:</strong>
  <%= @picture.pic_url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @picture.description %>
</p>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>