config/routes.rb
EslJobs::Application.routes.draw do
  get 'account/index'

  resources :company_employees

  resources :experiences

  get "school_search_results/index"
  resources :employee_search_results
  resources :school_search_results
  resources :job_search_results
  resources :videos

  resources :pictures

  resources :role_types

  resources :educations

  resources :reviews
  
  

  default_url_options :host => "/"
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
end
  get "advertise/index"
  get "contact/index"
  get "about/index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "job_types/index"
  get "home/index"
  get "countries/index"
  get "job_posts/index", :path => "esl-jobs"
  resources :job_posts, :path => "esl-teaching-jobs"
  resources :countries, :path => "esl-jobs"
  resources :job_types
  resources :about
  resources :contact
  resources :advertise

   root 'job_posts#index'
  get '/users/:id', :to => 'users#show', :as => :user
  resources :users

  

  
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
    user ||= User.new
    can :manage, :all if user.role == "admin"
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/country.rb
class Country < ActiveRecord::Base
  extend FriendlyId
  friendly_id :countryname, use: :history
  def should_generate_new_friendly_id?
    new_record?
  end
  
  has_many :job_posts
   validates :countryname, presence: true,
                    length: { minimum: 3 }
  def display_name
    countryname
  end
  

end

app/models/education.rb
class Education < ActiveRecord::Base
    validates_presence_of :school, :degree, :date, :user_id
end

app/models/experience.rb
class Experience < ActiveRecord::Base
end

app/models/job_post.rb
class JobPost < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :history
  def should_generate_new_friendly_id?
    new_record?
  end
  
  def normalize_friendly_id(string)
  super[0..80]
  end

  belongs_to :country
  belongs_to :job_type
  belongs_to :user
  validates_uniqueness_of :title
  validates :title, :description, :country_id, presence: true
  validates_length_of :description, :minimum => 50                  

  def self.search(search, countrysearch = nil)
    
    @countryid = Country.find_by(:countryname => countrysearch ) 
    
    if @countryid.blank?
        where('(title LIKE? OR description LIKE?)', "%#{search}%","%#{search}%")
    else
      where('(title LIKE? OR description LIKE?) AND country_id=?', "%#{search}%","%#{search}%", "#{@countryid.id }")
    end
  end
  
  def self.advancesearch(keyword = nil, countrysearch = nil, datesearch= nil)
    @countryid = Country.find_by(:countryname => countrysearch )
    where('(title LIKE? OR description LIKE?)', "%#{keyword}%","%#{keyword}%") if keyword.blank? 
    keywordsql= '(title LIKE\'%'+keyword+'%\' OR description LIKE\'%'+keyword+'%\')' unless keyword.blank?
    
    unless keyword.blank? || @countryid.blank?
    addand = ' AND '
    end
    
    unless keyword.blank? && @countryid.blank?
      unless datesearch.blank?
        dateand = ' AND '
      end
    end
    
    countrysql = addand.to_s + 'country_id ='+@countryid.id.to_s unless @countryid.blank?
    datesearch = dateand.to_s + '`created_at` BETWEEN \'' + datesearch.to_i.days.ago.to_s + '\' AND \'' + 0.days.ago.to_s + '\'' unless datesearch.blank?
    where(keywordsql.to_s+countrysql.to_s + datesearch.to_s)

  end

end

app/models/job_posts.rb
class JobPosts < ActiveRecord::Base
end

app/models/job_type.rb
class JobType < ActiveRecord::Base
  has_many :job_posts
  def display_name
    type_title
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
     mount_uploader :pic_url, AvatarUploader
    belongs_to :user
    
    validate :avatar_size_validation
     private
  
  def avatar_size_validation
    errors[:pic_url] << "should be less than 1MB" if pic_url.size > 1.megabytes
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
    validates_presence_of :rating, :reviewpost
end

app/models/role_type.rb
class RoleType < ActiveRecord::Base
    has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :pictures
  belongs_to :role_type
  has_many :job_posts
  mount_uploader :avatar, AvatarUploader
  validates :username, format: { with: /\A[a-zA-Z0-9]+\Z/ }
  validates_uniqueness_of :username
  validates :first_name, :last_name, :country ,presence: true
  include Mailboxer::Models::Messageable
  validates_length_of :first_name, :last_name , :maximum => 30
  validates_length_of :businessname, :maximum => 100
  
  validates_uniqueness_of :username

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  ROLES = %w[business individual]
  
  extend FriendlyId
  friendly_id :username
  
  
  acts_as_messageable

  def mailboxer_name(object)
  
  end

  def mailboxer_email(object)
     
  end
  
  def self.teacher_search(keyword = nil, countrysearch = nil)

    if countrysearch.blank?
      where('(username LIKE? OR first_name LIKE?)', "%#{keyword}%","%#{keyword}%")
    else
      where('(username LIKE? OR first_name LIKE?) AND country=?', "%#{keyword}%","%#{keyword}%", "#{countrysearch }")
    end
  end
  
end

app/models/video.rb
class Video < ActiveRecord::Base
    
end

app/controllers/educations_controller.rb
class EducationsController < InheritedResources::Base
  
  def create
  @education = Education.new(education_params)
 
  if @education.save
      redirect_to user_path(current_user) + '?back_to=eresume'  , notice: 'Education details was successfully Added.'
    else
      redirect_to user_path(current_user) + '?back_to=eresume', notice: 'Something wrong.'
    end
  end
  
  def destroy
  @education = Education.find(params[:id])
  @education.destroy
  redirect_to user_path(current_user) + '?back_to=eresume' , notice: 'Education details was successfully deleted.'
  end

  private

    def education_params
      params.require(:education).permit(:school, :degree, :date, :user_id).merge(:user_id => current_user.id)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mailbox_helper.rb
module MailboxHelper
  def unread_messages_count
    mailbox.inbox(:unread => true).count(:id, :distinct => true)
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/educations/_form.html.erb
  <div id="addeducation" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Add Education</h4>
      </div>
      <div class="modal-body">
         <%= form_for(@education) do |f| %>
  <div class="form-group">
     <label for="pwd">University/Collage/School Name</label>
      <%= f.text_field :school , :class => 'form-control' %>
  </div>
  <div class="form-group">
     <label for="pwd">Title of degree</label>
      <%= f.text_field :degree , :class => 'form-control' %>
  </div>
  <div class="form-group">
     <label for="pwd">Degree year duration</label>
     <%= f.text_field :date , :class => 'form-control' %>
  </div>
  
        </div>
      <div class="modal-footer">
        <button type="submit" class="send-msg">Add Education</button>
      </div>
    </div>
<% end %>
  </div>
</div>

app/views/educations/_index.html.erb
<% if @right_user %>
  <a href="#" class="btn btn-default button_center" data-toggle="modal" data-target="#addeducation">Add Education</a>
<% end %>
<% if !@right_user && @educations.blank? %>
   No Record Found
<% end %>
    <% @educations.each do |education| %>

                      <div class="education-row">
                        <%= link_to 'Destroy',  education,  method: :delete, data: { confirm: 'Are you sure?' }, :class=>"pull-right" %>
                        <h4><%= education.school %></h4>
                        <p><%= education.degree %></p>
                        <p class="edu-year"><%= education.date %></p>
                      </div>

    <% end %>

app/views/educations/edit.html.erb
<h1>Editing education</h1>

<%= render 'form' %>

<%= link_to 'Show', @education %> |
<%= link_to 'Back', educations_path %>

app/views/educations/new.html.erb
<h1>New education</h1>

<%= render 'form' %>

<%= link_to 'Back', educations_path %>

app/views/educations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>School:</strong>
  <%= @education.school %>
</p>

<p>
  <strong>Degree:</strong>
  <%= @education.degree %>
</p>

<p>
  <strong>Date:</strong>
  <%= @education.date %>
</p>

<%= link_to 'Edit', edit_education_path(@education) %> |
<%= link_to 'Back', educations_path %>